name: ci

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        varnish: ['6.0', '7.0', '7.1']

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt-get
      run: |
        sudo apt-get update
        sudo apt-get install -y libedit-dev python3-docutils python3-sphinx
    - name: prereq
      run: |
        cd libmaxminddb && ./bootstrap && ./configure && make && sudo make install && cd ..
        git clone -b ${{ matrix.varnish }} https://github.com/varnishcache/varnish-cache.git
        cd varnish-cache && ./autogen.sh && ./configure && make && sudo make install && sudo ldconfig && cd ..
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure CFLAGS="-Wall -Wextra -Werror"
    - name: make
      run: make
    - name: make check
      run: make check VERBOSE=1
      continue-on-error: true
